# use cicd-microservice container
image: cbiitssrepo/cicd-microservice:latest

setenv:
  stage: setenv
  variables:
    ENVIRONMENT: bento-gitlab
  script: echo "ENVIRONMENT=$ENVIRONMENT" >> build.env
  artifacts:
    reports:
      dotenv: build.env

#buildanddeploy:
#  stage: buildanddeploy
#  variables:
#    ENVIRONMENT: bento-gitlab
#  script: ansible-playbook devops/ansible/bento-deploy.yml -i devops/ansible/hosts

deploy:
  stage: deploy
  variables:
    ENVIRONMENT: bento-gitlab
  trigger: bento-frontend/deploy
  dependencies:
    - setenv