# use cicd-microservice container
image: cbiitssrepo/cicd-microservice:latest

stages:
  - bridge

#setenv:
#  stage: .pre
#  variables:
#    ENVIRONMENT: bento-gitlab
#  script: echo "ENVIRONMENT=$ENVIRONMENT" >> build.env
#  artifacts:
#    reports:
#      dotenv: build.env

#buildanddeploy:
#  stage: buildanddeploy
#  variables:
#    ENVIRONMENT: bento-gitlab
#  script: ansible-playbook devops/ansible/bento-deploy.yml -i devops/ansible/hosts

Bridge to Frontend:
  stage: bridge
#  variables:
#    ENVIRONMENT: bento-gitlab
  trigger:
    project: bento-frontend
    branch: gitlab-testing
#  needs:
#    - job: setenv
#      artifacts: true