pipeline {
    agent {
        node {
            label 'docker-ansible'
            }
        }
    parameters {

    gitParameter(branchFilter: 'origin/(.*)', 
        defaultValue: 'JenkinsBranch', 
        name: 'Tag', 
        type: 'PT_BRANCH_TAG',
        quickFilterEnabled: false, 
        selectedValue: 'DEFAULT', 
        sortMode: 'ASCENDING_SMART', 
        tagFilter: '*', 
        useRepository: 'https://github.com/CBIIT/DataCommons_Automation')

    string(defaultValue: "CTDC_Automation/CTDC_Automation.prj", 
        description: 'Enter the Katalon Project file (include the path relative to the repo root):', 
        name: 'KatalonPrj')

    string(defaultValue: "Test Suites/Canine_TestSuite", 
        description: 'Enter the Katalon Suite Path (not including the test suite file):', 
        name: 'KatalonSuite')

    extendedChoice( 
        name: 'Browser', 
        defaultValue: 'chrome', 
        description: 'Choose the browser (headless) to use', 
        type: 'PT_SINGLE_SELECT',
        value: 'chrome,firefox' )

        }
    // options {
    // 	ansiColor('xterm')
    // }
    tools {
        jdk 'Default' 
        }
    stages{
        stage('checkout'){
            steps {

                checkout([$class: 'GitSCM', 
                    branches: [[name: "${params.Tag}"]], 
                    doGenerateSubmoduleConfigurations: false,
					extensions: [],
					submoduleCfg: [], 
                    userRemoteConfigs: [[url: 'https://github.com/CBIIT/DataCommons_Automation']]])

                dir('icdc-devops'){
                    git branch: 'master',
                    url: 'https://github.com/michael-fleming/DevOps.git'}

                }
            }
		stage('set Password File'){
			steps {
                script {
                    switch("${params.Browser}") {
                    case "firefox":
                        withCredentials([file(credentialsId: 'Katalon_Pass_FFHeadless', variable: 'pass_file')]) {
                            sh "cp ${pass_file} ${WORKSPACE}/CTDC_Automation/TestData/Password_canine.xlsx"
                            }
                        break
                    case "chrome":
                        withCredentials([file(credentialsId: 'Katalon_Pass_CHHeadless', variable: 'pass_file')]) {
                            sh "cp ${pass_file} ${WORKSPACE}/CTDC_Automation/TestData/Password_canine.xlsx"
                            }
                        break
                    }
				}
			}
        stage('run tests'){
            environment {
                SLACK_URL           =   ""
                KATALON_PRJ         =   "${params.KatalonPrj}"
                KATALON_SUITE_PATH  =   "${params.KatalonSuite}"
                }
            steps {

                sh label: 'Katalon-Tests', script: '''#!/bin/bash
				
                    # Set datestamp for results file
                    dateStamp=$(date +%Y%m%d%H%M)

					# Get required browser and driver
                    #wget https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm && yum -y install ./google-chrome-stable_current_*.rpm
                    #wget https://chromedriver.storage.googleapis.com/81.0.4044.69/chromedriver_linux64.zip && mv CTDC_Automation/chromedriver.exe CTDC_Automation/chromedriver.exe.bak && unzip chromedriver_linux64.zip -d CTDC_Automation/
                    #google-chrome --version
                    yum -y install firefox

                    # Get Katalon Runtime Engine
                    wget https://github.com/katalon-studio/katalon-studio/releases/download/v7.2.6/Katalon_Studio_Engine_Linux_64-7.2.6.tar.gz && tar -xvzf Katalon_Studio_Engine_Linux_64-7.2.6.tar.gz && mv Katalon_Studio_Engine_Linux_64-7.2.6 katalon && chown -R root:root katalon

                    # Recreate the results directory
                    rm -rf results && mkdir results

                    # Run Katalon Tests
                    #katalon/katalonc -noSplash  -runMode=console -projectPath= "$WORKSPACE/$KATALON_PRJ" -retry= 0 -testSuitePath= "$KATALON_SUITE_PATH" -browserType= "Chrome (headless)" -reportFolder="$WORKSPACE/results" -reportFileName="index_$dateStamp" -apiKey=1d9d7e79-dde9-45c1-9d21-b31424a47864
					katalon/katalonc -noSplash  -runMode=console -projectPath= "$WORKSPACE/$KATALON_PRJ" -retry= 0 -testSuitePath= "$KATALON_SUITE_PATH" -browserType= "Firefox (headless)" -reportFolder="$WORKSPACE/results" -reportFileName="index_$dateStamp" -apiKey=1d9d7e79-dde9-45c1-9d21-b31424a47864

                    '''

                }
            }
		
        }
		post {
			always {

				publishHTML([allowMissing: true,
					alwaysLinkToLastBuild: false,
					keepAll: false,
					reportDir: 'results',
					reportFiles: 'inex_*.html',
					reportName: 'HTML Report',
					reportTitles: ''])

                emailext(attachmentsPattern: 'results/index_*.html',
                    body: 'Katalon Test Results',
                    subject: 'Katalon Test Results',
                    to: 'Katalon.w1imuj982tottg1c@u.box.com')

				}
			}
	}